[package]
name = "adaptive-dots"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Alexander Busch"]
license = "MIT"
description = "Adapt ellipsis dots to centered or baseline based on context in typst, like LaTeX amsmath."
repository = ""
keywords = ["typst", "math", "dots", "ellipsis", "amsmath"]
categories = ["text", "scripting"]
exclude = ["test.typ", "spec.md"]
